[server]
port = 7777
ip = 64.188.70.158 
sync_psk = BQQCyN8zo4La2lRSIQ2jLp5imEa0JzdXp2PKogP3   # P2P cluster authentication key (optionally)

# Per-key command sections (Recommended)
#[exec_commands:RWTPQzuhzBw=]
#<key> = <script_path> time_limit = <sec>
#start_app = /usr/local/bin/app_start.sh time_limit = 60
#
# Global commands (Available to all keys)
#[exec_commands]
#sysadmin = /usr/local/bin/gorgona_sysadmin.sh time_limit = 10
#status = /usr/bin/uptime
