[server]
port = 7777                      # Listen port (default: 5555)
max_alerts = 1000                # Max alerts stored per recipient key
max_clients = 100                # Max simultaneous TCP connections
max_message_size = 5             # Max message size in MB (default: 5)
use_disk_db = true               # Enable persistent storage in /var/lib/gorgona/alerts/
vacuum_threshold_percent = 25    # Auto-cleanup threshold for deleted/expired alerts

# Logging levels:
# error: Only critical errors.
# info : Connections, disconnections, and status changes (Default).
# debug: Full trace including raw command payloads and message metadata.
log_level = info                 
max_log_size = 10                # Log rotation limit in MB

[replication]
sync_psk = BQQCyN8zo4La2lRSIQ2jLp5imEa0JzdXp2PKogP3 # sync_node_password 
peer = 192.168.1.200:7777
